#!/bin/sh -x
WAXEYE_HOME="$HOME/bin/waxeye-0.8.0"

waxeye -g java src/generated -n generated address.waxeye &&
cd src &&
javac \
  -cp .:$WAXEYE_HOME/lib/waxeye.jar \
  -Xdiags:verbose \
  *.java && # ../src/generated/*.java &&

cat << EOF |
Sé Ó út 1.2.ép.A.lph.4.ajtó 9876/5/A/42.hrsz.
9999 2483 2483 Gárdony Balatoni utca 1/a. 2. emelet 3. ajtó V2 üzlet
EOF

java -cp .:$WAXEYE_HOME/lib/waxeye.jar Address > out.canon.txt
